name: CI

on:
  workflow_dispatch:
#   push:
#     branches:
#       - trunk

jobs:
  checks:
    name: Checks
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x]

    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Setup pnpm
        uses: pnpm/action-setup@v1.2.0
        with:
          version: 5.4.11

      - name: Install depedencies
        run: pnpm install

      - name: Lint packages
        run: pnpm run lint --recursive

      - name: Run tests
        run: pnpm run test --recursive

      - name: Build gatsby-source-takeshape
        run: pnpm run build --filter gatsby-source-takeshape
