name: Issue Housekeeping

on:
  issues:
    types:
      - opened

jobs:
  add_new_issue_to_column:
    runs-on: ubuntu-latest
    steps:
      - uses: konradpabjan/actions-add-new-issue-to-column@v1.1
        with:
          action-token: ${{ secrets.ORG_PROJECT_TOKEN }}
          project-url: https://github.com/orgs/takeshape/projects/2
          column-name: Backlog
