name: PR Housekeeping

on:
  pull_request:
    types: [assigned, opened, synchronize, reopened, edited, closed]

jobs:
  assign_author:
    runs-on: ubuntu-latest
    steps:
      - name: Assign author to PR
        if: ${{ github.event.action == 'opened' }}
        uses: technote-space/assign-author@v1

  add_an_issue_reference:
    runs-on: ubuntu-latest
    steps:
      - uses: kentaro-m/add-an-issue-reference-action@v2.0.0
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          branch-prefix: issue-
