name: PR Housekeeping

on:
  pull_request:
    types: [assigned, opened, synchronize, reopened, edited, closed]

jobs:
  assign-author:
    runs-on: ubuntu-latest
    steps:
      - name: Assign author to PR
        if: ${{ github.event.action == 'opened' }}
        uses: technote-space/assign-author@v1

  issue-link:
    runs-on: ubuntu-latest
    steps:
      - uses: tkt-actions/add-issue-links@v1.2.0
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          branch-prefix: issue-
          position: top
          resolve: true
